(source melpa)

(package "package-name" "1.7.0" "Package description.")

(development
 (depends-on "f")
 (depends-on "s")
 (depends-on "dash")
 (depends-on "el-mock")
 (depends-on "ert-runner")
 (depends-on "ecukes")
 (depends-on "espuds"))
